version: '2'
services:
    golfdistance-app:
        image: golfdistance
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://golfdistance-postgresql:5432/golfDistance
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    golfdistance-postgresql:
        extends:
            file: postgresql.yml
            service: golfdistance-postgresql
